CMake fixes
DanBloomberg/leptonica pull request #599
Opened 2021-12-04 08:56 UTC by diizzyy

Make lib(WebP) and OpenJPEG support optional
Report correct version in generated .pc file

2021-12-04 08:58 UTC, diizzyy commented
You're free to change whether these should be enabled or disabled by default

2021-12-04 09:06 UTC, zdenop commented
What is the rationale behind this? Why do you turn them off by default?

2021-12-04 09:48 UTC, diizzyy commented
As I said, feel free to use whatever option as you set fit as default. The main point is to make sure they aren't pulled in unintentionally.

2021-12-04 14:46 UTC, diizzyy commented
Remaning issues:
Library symlinks are a bit weird/inconsistent to autotools

```
lrwxr-xr-x  1 root  wheel       21 Dec  4 15:44 libleptonica.so -> libleptonica.so.5.4.0
-rwxr-xr-x  1 root  wheel  2849560 Dec  4 15:44 libleptonica.so.1.82.0
lrwxr-xr-x  1 root  wheel       22 Dec  4 15:44 libleptonica.so.5.4.0 -> libleptonica.so.1.82.0
```

2021-12-05 19:45 UTC, DanBloomberg commented
@egorpugin @stweil @zdenop
There are 5 relatively minor changes to cmake in this PR.
Do you have any issues with them?

Two questions:
(1) I don't know anything about private libs in cmake.  Are they useful?  Suggest that if they are adopted, the default be ON for jp2k and webp.
(2) Is there any reason for the use of the version number (e.g., 1.82.0) instead of the so number in the name of the library?

2021-12-05 19:50 UTC, diizzyy commented
Private.libs matters because if you have a downstream user that looks for the pc file (pkgconfig) it'll break.
As for so number this should be consistent with autotools

2021-12-08 19:49 UTC, stweil commented on CMakeLists.txt
> +            set(libs_private "-lgif")
```suggestion
            set(libs_private "${libs_private} -lgif")
```

2021-12-08 19:51 UTC, stweil commented on CMakeLists.txt
> +        if(GIF_FOUND)
Why are this and the other `if` blocks not on the same indentation level as `find_package`?

2021-12-08 19:55 UTC, stweil requested changes

2021-12-08 19:55 UTC, stweil commented on CMakeLists.txt
> +    option(OPENJPEG_SUPPORT "Build with OpenJPEG support" OFF)
```suggestion
    option(LIBWEBP_SUPPORT "Build with WebP support" ON)
    option(OPENJPEG_SUPPORT "Build with OpenJPEG support" ON)
```

2021-12-08 20:07 UTC, diizzyy commented on CMakeLists.txt
> +            set(libs_private "-lgif")
Is that correct since it's initializing the variable?

2021-12-08 20:10 UTC, diizzyy commented on CMakeLists.txt
> +        if(GIF_FOUND)
Good catch, I'll correct that

2021-12-08 20:10 UTC, stweil commented on CMakeLists.txt
> +            set(libs_private "-lgif")
It isn't, unless `GIF_FOUND` was true. Any of the following `set` statements could initialize it if all preceding `if` blocks are false.

2021-12-08 20:16 UTC, stweil commented on CMakeLists.txt
> +            set(libs_private "-lgif")
You could initialize `libs_private` before the first `if` block to an empty string if necessary. The resulting value of `libs_private` can have a leading space. I don't know whether that is a problem.

2021-12-08 20:47 UTC, diizzyy commented
@stweil 
Fixed, thanks for reviewing!

2021-12-13 09:10 UTC, diizzyy commented
Anything else that needs to be done and/or adjusted?

2021-12-27 13:01 UTC, diizzyy commented
Friendly ping

2021-12-27 21:06 UTC, DanBloomberg commented
Daniel, approving your PR is above my pay grade.  The only build system I maintain is the hand-tweaked makefiles.
My impression of the changes:
Make lib(WebP) and OpenJPEG support optional:       ok with default ON
Report correct version in generated .pc file:                  seems reasonable
Populate Libs.private in .pc file:                                     seems reasonable
Properly define library version:                                      good to follow standards
Install imagetops for consistency with Autotools build:  ok

Anyone want to approve or suggest changes?

2021-12-29 20:57 UTC, stweil commented
> I don't know anything about private libs in cmake. Are they useful?

`lept.pc` on Debian has `Libs.private: -lz -lpng16 -lz -ljpeg -lopenjp2 -lgif -ltiff -lwebp -lwebpmux -lwebp` (note that `-lwebp` is unnecessarily duplicated), so adding the same libraries in cmake builds looks correct.

I'm afraid I cannot say much to the remaining changes as I don't think that I am an expert for cmake. @egorpugin and @zdenop contributed most to `CMakeLists.txt`

2021-12-29 20:58 UTC, merged

2022-02-06 21:59 UTC, DanBloomberg commented
@diizzyy 

Please look at
   https://github.com/tesseract-ocr/tesseract/issues/3738

While trying to resolve that issue, we're brought back to the various library naming issues.